### ISSUE TITLE
Add a common formatter

### ISSUE THREAD

**Issue by Hacaw** [azerothcore/wow-statistics#19]
Given the fact we are using different OS/IDE we have different formatting, so we should agree upon a standard one.

- to have consistency between different IDEs
- to have consistency between different OS
+ format the entire code base with it

**Comment by Helias** [comment]
we could use **prettier**, it's available in multiple IDE even in the JetBrains IDE
https://prettier.io/docs/en/editors.html

**Comment by Hacaw** [comment]
I think we are also using ESLint given the fact the app was boostraped with CRA.
I will look into https://github.com/prettier/eslint-config-prettier#installation.

**Comment by Hacaw** [comment]
@Helias , adding prettier was pretty easy.

I also tried to add husky + commit-lint, to enforce the conventional commit paradigm, but it's not working at all at least on my machine.
See https://github.com/typicode/husky/issues/557 which is the same on my machine.
I have win 10 - node 14.x , npm 6.x.

**Comment by Helias** [comment]
husky is a good choice to force some regex in the commit name, we could add it here locally and in the pipeline
and maybe... we could find a way to force the convetions in AzerothCore too ;-)
